### ISSUE TITLE
GPL is dangerous

### ISSUE THREAD

**Issue by starshipjc** [andyburke/UnityHTTP#37]
By using this library, projects theoretically MUST publish their source code when they distribute their application. As most games are closed-source, this makes this library unusable. It also means they should not be published on the iOS app store.

**Comment by simonwittber** [comment]
GPL is fine for open projects, students etc. If your game is closed, then the closed option is to purchase a license of UniWeb which is the progenitor of this project. 

:: Simon Wittber
:: Director
:: Different Methods Pty Ltd

**Comment by starshipjc** [comment]
Thanks for the reply Simon,

Ah, if that is possible, excellent. I didn't find it on the AssetStore initially, and the Google site looked like it was abandoned! Expect a sale.
