### ISSUE TITLE
Cannot integrate UnityHTTP in Version 5.0.1f1

### ISSUE THREAD

**Issue by flyrev** [andyburke/UnityHTTP#38]
I get compile errors when trying to integrate UnityHTTP in my project.

Steps:
`cd Library/Plugins`

`git clone git@github.com:andyburke/UnityHTTP.git`

I then get the error

```
Assets/Plugins/UnityHTTP/src/Request.cs(80,13): error CS0030: Cannot convert type `System.Collections.Generic.KeyValuePair<string,string>' to `System.Collections.DictionaryEntry'
```

What is wrong? It Unity 5 not supported? Should the code reside in a different place? Is there a different import process I should use?

**Comment by franzbischoff** [comment]
Unity5 (I don't know about Unity 4) has this class field:
http://docs.unity3d.com/ScriptReference/WWWForm-headers.html

with type Dictionary<string,string>

You must edit the line 80 and change from this:
foreach ( DictionaryEntry entry in form.headers )
to this:
foreach ( KeyValuePair<string,string> entry in form.headers )

**Comment by romansavrulin** [comment]
or just
```csharp
foreach ( var entry in form.headers )
```

**Comment by flyrev** [comment]
Thanks
