### ISSUE TITLE
"you must use the Request synchronously, since Unity's main update loop is not running"

### ISSUE THREAD

**Issue by cmisztur** [andyburke/UnityHTTP#47]
This actually is not true.
It is true that Time.deltaTime does not change but there are ways around it.

```
UnityEditor.EditorApplication.update += this.Update;
```
in combination with...
```
UnityEditor.EditorUtility.SetDirty(x)
```

**Comment by andyburke** [comment]
I would welcome a PR that would allow something like this to happen automatically if not in play mode. But for now, I'm going to close this issue since it would require the user to effectively handle the update themselves.
