### ISSUE TITLE
POSTing file causes error

### ISSUE THREAD

**Issue by ryansp** [andyburke/UnityHTTP#49]
This library doesn't seem to be able to handle files, only strings. I am including a PNG's bytes as a field in a WWWForm and receiving the following error:

InvalidCastException: Cannot cast from source type to destination type.
HTTP.Request..ctor (System.String method, System.String uri, UnityEngine.WWWForm form) (at Assets/Scripts/HTTP/Request.cs:92)

Is this expected behavior? How hard would it be to add file support?

**Comment by andyburke** [comment]
Did you figure this out? What happened with this issue?

**Comment by ryansp** [comment]
Sorry about that - I jumped the gun and it turns out it was the issue I posted in #50. Wasn't sure how to delete this issue. File upload seems to work.
