### ISSUE TITLE
HTTP Request with WWWForm fails with error

### ISSUE THREAD

**Issue by ryansp** [andyburke/UnityHTTP#50]
When using a WWWForm in a request, it fails when parsing the headers. This is because it is looking for a KeyValuePair in a hashtable: 

foreach ( KeyValuePair<string,string> pair in form.headers )
{
    this.AddHeader(pair.Key,pair.Value);
}

Can be fixed by using DictionaryEntry instead:

foreach ( DictionaryEntry entry in form.headers )
{
    this.AddHeader(entry.Key.ToString(), entry.Value.ToString());
}

**Comment by andyburke** [comment]
This looks related to #48 by @codeMonkeyWang. @codeMonkeyWang any ideas?

**Comment by codeMonkeyWang** [comment]
I think #51 is good @andyburke

**Comment by andyburke** [comment]
Should be addressed by #51
