### ISSUE TITLE
How to import this into a Unity 5 project?

### ISSUE THREAD

**Issue by luciomartinez** [andyburke/UnityHTTP#56]
Hello! I have been all day trying to figure out how to import this project into a Unity 5 project but couldn't find the way.

I've tried to add as reference, but the project is not displayed. Also as a side project, but then and for some reason `using` can't find the classes (maybe it fails to compile because missing dependencies?).

Is there a guide for Unity 4? That will probably be the same thing.

PS: I hope you tag this a question only, not an actual bug :)

**Comment by enriqif** [comment]
Could you add it to your project?

Did you try just copy and paste source code into assets folder?

**Comment by luciomartinez** [comment]
not reproducible anymore, thanks.
